### ISSUE TITLE
Error "controller.py line 7: No module named 'remote_call'" while trying to enable plugin in Maya

### ISSUE THREAD

**Issue by itsgundie** [ihoung/Maya2UnrealExportTool#1]
Plugin is located  at "..\Documents\maya\Maya2UnrealExportTool" when trying to activate in plugins window of Maya 2022.2 it failes with next message:
```
// Error: file: C:/Program Files/Autodesk/Maya2022/scripts/others/pluginWin.mel line 316: ModuleNotFoundError: file C:\Users\Gundie\Documents\maya\Maya2UnrealExportTool\plug-ins\core\controller.py line 7: No module named 'remote_call' // 
// Warning: file: C:/Program Files/Autodesk/Maya2022/scripts/others/pluginWin.mel line 316: Failed to run file: C:/Users/Gundie/Documents/maya/Maya2UnrealExportTool/plug-ins/M2UExportTool.py // 
// Error: file: C:/Program Files/Autodesk/Maya2022/scripts/others/pluginWin.mel line 316:  (M2UExportTool) // 
```

**Comment by ihoung** [comment]
The python environment on Maya 2022 is python3, which is entirely different from old versions. This plugin was only tested on Maya's old versions which are on python2. Nothing you can do to change Maya script environment and I need to take time to make the plugin compatible for python3
